version: "3"
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    restart: always
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    networks: 
      - hadoop
    env_file: 
      - ./hadoop.env
    ports:
      - 50070:50070
      - 8020:8020
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    restart: always
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    networks: 
      - hadoop
    ports:
      - 50075:50075
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    networks: 
      - hadoop
    env_file:
      - ./hadoop.env
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    restart: always
    env_file:
      - ./hadoop.env
    command: hive --service hiveserver2
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
    networks: 
      - hadoop
    ports:
      - 10000:10000
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: always
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    networks: 
      - hadoop
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: postgres:11-alpine
    container_name: hive-metastore-postgresql
    restart: always
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    networks: 
      - hadoop
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-hive-db.sql:/docker-entrypoint-initdb.d/init-hive-db.sql
  hue:
    image: gethue/hue:latest
    container_name: hue
    restart: always
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083 hive-server:10000"
    networks: 
      - hadoop
    ports:
      - 8888:8888
    volumes:
      - ${PWD}/opt/hue_conf/hue.ini:/usr/share/hue/desktop/conf/hue.ini
      - ${PWD}/opt/hue_conf/zoo.cfg:/etc/zookeeper/conf/zoo.cfg
      - ${PWD}/opt/hue_conf/zookeeper.service:/etc/systemd/system/zookeeper.service
      - ${PWD}/opt/hue_conf/zoo.cfg:/opt/zookeeper/conf/zoo.cfg
      - ${PWD}/opt/hue_conf/zoo.cfg:/opt/zookeeper/apache-zookeeper-3.8.1-bin/conf/zoo.cfg
networks:
  hadoop:
    driver: bridge
volumes:
  namenode:
  datanode:
  postgres_data:
